steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Prime Maven cache'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - 'gs://hmf-build-caches/platinum/.m2'
      - '/cache/.m2'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'

  - name: 'maven:3-jdk-11'
    id: 'Set version for Maven'
    entrypoint: mvn
    args: [ 'versions:set', '-DnewVersion=${SHORT_SHA}' ]

  - name: 'gcr.io/cloud-builders/mvn'
    id: 'Deploy JAR to Maven'
    args:
      - 'deploy'
      - '-Drelease'
      - '--batch-mode'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2

  - name: 'gcr.io/cloud-builders/docker'
    id: Build Platinum image
    args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/platinum:${SHORT_SHA}', '.', '--build-arg', 'VERSION=${SHORT_SHA}' ]

  - name: 'gcr.io/cloud-builders/docker'
    id: Push Platinum image
    entrypoint: '/bin/bash'
    args: [ '-c', "docker", "push", "eu.gcr.io/$PROJECT_ID/platinum:${SHORT_SHA}" ]

  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '/cache/.m2'
      - 'gs://hmf-build-caches/platinum/.m2/'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
options:
  machineType: 'N1_HIGHCPU_32'
images:
  - eu.gcr.io/$PROJECT_ID/platinum
