steps:
  - id: 'Prime Maven cache'
    name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - 'gs://hmf-build-caches/platinum/.m2'
      - '/cache/.m2'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
  - id: 'Set version for Maven'
    name: 'maven:3.9.2-eclipse-temurin-11'
    entrypoint: mvn
    args: [ 'versions:set', '-DnewVersion=${SHORT_SHA}' ]
  - id: 'Compile, package, release'
    name: 'maven:3.9.2-eclipse-temurin-11'
    entrypoint: mvn
    args:
      - 'deploy'
      - '-Drelease'
      - '--batch-mode'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2
  - id: 'Publish Docker image'
    name: 'eu.gcr.io/hmf-build/docker-tag'
    args: ['eu.gcr.io/hmf-build/platinum', '$TAG_NAME', 'Dockerfile']
  - id: 'Refresh bucket from local Maven cache after build'
    name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '/cache/.m2'
      - 'gs://hmf-build-caches/platinum/.m2/'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
options:
  machineType: 'E2_HIGHCPU_8'
images:
  - eu.gcr.io/hmf-build/platinum
