apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pv5-
spec:
  entrypoint: main-loop
  volumes:
  - name: patient-json
    configMap:
      name: patient-jsons
  - name: platinum-bootstrap-key
    secret:
      secretName: platinum-bootstrap-key
  templates:
  - name: main-loop
    steps:
    - - name: launch
        template: pipeline
        arguments:
          parameters:
          - name: patient
            value: "{{item}}"
        withItems: 
        - CPCT12345678
        - CPCT34567890

  - name: pipeline
    inputs:
      parameters:
      - name: patient
    container:
      image: hartwigmedicalfoundation/pipeline5:5.12.1646
      volumeMounts:
      - name: patient-json
        mountPath: "/secrets/patients"
      - name: platinum-bootstrap-key
        mountPath: "/secrets/"
      command: ["/pipeline5.sh"]
      args: ["-project", "hmf-pipeline-development", 
             "-service_account_email", "bootstrap@hmf-pipeline-development.iam.gserviceaccount.com", 
             "-patient_report_bucket", "platinum-output-dev",
             "-private_network", "default",
             "-private_key_path", "secrets/platinum-bootstrap-key",
             "-cmek", "projects/hmf-pipeline-development/locations/europe-west4/keyRings/hmf-pipeline-development/cryptoKeys/default-test",
             "-publish_to_turquoise", "false",
             "-sample_json", "/secrets/patients/{{inputs.parameters.patient}}.json", 
             "-set_id", "{{inputs.parameters.patient}}"]
