apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pv5-
spec:
  entrypoint: main-loop
  templates:
  - name: main-loop
    steps:
    - - name: launch
        template: pipeline
        arguments:
          parameters:
          - name: patient
            value: "{{item}}"
        withItems: 
        - CPCT12345678
        - CPCT34567890

  - name: pipeline
    inputs:
      parameters:
      - name: patient
    container:
        image: hartwigmedicalfoundation/pipeline5:5.12.1646
      command: ["echo"]
      args: ["/pipeline5.sh", -project", "-hmf-pipeline-development", 
             "-service_account_email", "bootstrap@hmf-pipeline-development.iam.gserviceaccount.com", 
             "-patient_report_bucket", "pipeline-output-dev",
             "-private_network", "default",
             "-private_key_path", "source/hartwig/credentials/hmf-pipeline-development.json",
             "-cmek", "projects/hmf-pipeline-development/locations/europe-west4/keyRings/hmf-pipeline-development/cryptoKeys/default-test",
             "-publish_to_turquoise", "false"
             "-sample_json", "cancerPanel.json", 
             "-set_id", "{{inputs.parameters.patient}}"]
