#!/usr/bin/env bash

function install {
    ./mvnw clean install -DskipTests
}

function run {
    export SUPPRESS_GCLOUD_CREDS_WARNING=true
    JAR=./target/platinum-local-SNAPSHOT.jar
    if [ ! -f $JAR ]; then
      install
    fi
    java -jar $JAR "$@"
}

CMD=$1
shift

case $CMD in
install)
  install
  ;;
run)
  run "$@"
  ;;
esac