apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pv5-
spec:
  entrypoint: main-loop
  volumes:
  - name: patient-json
    configMap:
      name: patient-jsons
  - name: platinum-bootstrap-key
    secret:
      secretName: platinum-bootstrap-key
  templates:
  - name: main-loop
    steps:
    - - name: launch
        template: pipeline
        arguments:
          parameters:
          - name: patient
            value: "{{item}}"
        withItems: 
        - CPCT02010003
        - CPCT02010022
        - CPCT02010035
        - CPCT02010037
        - CPCT02010043
        - CPCT02010050
        - CPCT02010063
        - CPCT02010122
        - CPCT02010123
        - CPCT02010134
        - CPCT02010173
        - CPCT02010233
        - CPCT02010238
        - CPCT02010240
        - CPCT02010246
        - CPCT02010249
        - CPCT02010250
        - CPCT02010252
        - CPCT02010257
        - CPCT02010262
        - CPCT02010266
        - CPCT02010268
        - CPCT02010269
        - CPCT02010272
        - CPCT02010273
        - CPCT02010281
        - CPCT02010288
        - CPCT02010289
        - CPCT02010298
        - CPCT02010299
        - CPCT02010300
        - CPCT02010304
        - CPCT02010313
        - CPCT02010320
        - CPCT02020171
        - CPCT02020187
        - CPCT02020194
        - CPCT02020195
        - CPCT02020197
        - CPCT02020202
        - CPCT02020203
        - CPCT02020207
        - CPCT02020210
        - CPCT02020212
        - CPCT02020213
        - CPCT02020215
        - CPCT02020217
        - CPCT02020218
        - CPCT02020219
        - CPCT02020220
        - CPCT02020231
        - CPCT02020236

  - name: pipeline
    inputs:
      parameters:
      - name: patient
    container:
      image: hartwigmedicalfoundation/pipeline5:5.13.1672
      volumeMounts:
      - name: patient-json
        mountPath: "/secrets/patients"
      - name: platinum-bootstrap-key
        mountPath: "/secrets/"
      command: ["/pipeline5.sh"]
      args: ["-project", "hmf-crunch", 
             "-service_account_email", "hmf-crunch@hmf-crunch.iam.gserviceaccount.com", 
             "-patient_report_bucket", "platinum-output-crunch",
             "-private_network", "default",
             "-private_key_path", "secrets/platinum-bootstrap-key",
             "-cmek", "projects/hmf-database/locations/europe-west4/keyRings/hmf-database/cryptoKeys/hmf-database-20191001",
             "-publish_to_turquoise", "false",
             "-ref_genome_version", "HG38",
             "-max_concurrent_lanes", "2",
             "-poll_interval", "30",
             "-output_cram", "false",
             "-run_snp_genotyper", "false",
             "-sample_json", "/secrets/patients/{{inputs.parameters.patient}}.json", 
             "-set_id", "{{inputs.parameters.patient}}"]
